# Generated by Django 5.1.6 on 2025-12-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
