# Generated by Django 5.1.6 on 2025-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(help_text='Год'),
        ),
    ]
